spring:
  cloud:
    compatibility-verifier:
      enabled: false

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true
    eureka-server-port: 8761