spring:
  cloud:
    compatibility-verifier:
      enabled: false

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true
    eureka-server-port: 8761

management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
    jmx:
      exposure:
        include: '*'